//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarCollection
    {
        public int CarId { get; set; }
        public string CarMkModel { get; set; }
        public string Engine { get; set; }
        public string BodyType { get; set; }
        public string Transmission { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public string Value { get; set; }
    }
} 
